kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    cluster: management
    component: device-manager
  name: device-manager
  namespace: __NPH_NAMESPACE
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      cluster: management
      component: device-manager
  template:
    metadata:
      labels:
        cluster: management
        component: device-manager
    spec:
      containers:
      - name: device-api
        image: __NPH_REGISTRY.azurecr.io/__NPH_REGISTRY_NAMESPACE/device-manager:__NPH_VERSION
        imagePullPolicy: Always
        args:
        - "run"
        - "--debug"
        - "--useDBScyllaProviders=true"
        - "--scyllaDBAddress=scylladb.__NPH_NAMESPACE"
        - "--scyllaDBKeyspace=measure"
        - "--scyllaDBPort=9042"
        - "--systemModelAddress=system-model.__NPH_NAMESPACE:8800"
        - "--authxAddress=authx.__NPH_NAMESPACE:8810"
        securityContext:
          runAsUser: 2000
      imagePullSecrets:
      - name: nalej-registry
