kind: Service
apiVersion: v1
metadata:
  name: device-manager
  labels:
    cluster: management
    component: device-manager
  namespace: __NPH_NAMESPACE
spec:
  selector:
    cluster: management
    component: device-manager
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 6010
    targetPort: 6010
    name: grpc
