kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    cluster: management
    component: device-manager
  name: device-manager
  namespace: __NPH_NAMESPACE
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      cluster: management
      component: device-manager
  template:
    metadata:
      labels:
        cluster: management
        component: device-manager
    spec:
      containers:
      - name: device-api
        image: nalejregistry.azurecr.io/nalej/device-manager:__NPH_VERSION
        imagePullPolicy: Always
        args:
        - "run"
        - "--debug"
        - "--systemModelAddress=system-model.nalej:8800"
        - "--authxAddress=authx.nalej:8810"
        securityContext:
          runAsUser: 2000
      imagePullSecrets:
      - name: nalej-registry
