apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    cluster: management
  name: device-manager-scylla
  namespace: __NPH_NAMESPACE
data:
  device-manager-scylla.cql: |
    --------------
    -- KEYSPACE --
    --------------
    create KEYSPACE IF NOT EXISTS measure WITH replication = {'class': 'SimpleStrategy', 'replication_factor': 3};
    Create table IF NOT EXISTS measure.latency (organization_id text, device_group_id text, device_id text, inserted bigint, latency int, PRIMARY KEY ((organization_id, device_group_id), device_id, inserted) );
    Create materialized view IF NOT EXISTS measure.deviceGrouplatency as  select * from measure.latency where organization_id is not null and device_group_id is not null and inserted is not null and device_id is not null primary key ((organization_id, device_group_id), inserted, device_id);
  node_alive.sh: |
    #!/bin/bash
        sleep_time=15
        echo 'executing script...'
        KEYSPACE=$(cqlsh scylladb -e "DESCRIBE KEYSPACES")
        while [ $? -ne 0 ]
        do
          echo 'waiting'  ${sleep_time}
          sleep $sleep_time
          case $sleep_time in
            15)
                sleep_time=10
            ;;
            **)
              sleep_time=5
            ;;
         esac
          KEYSPACES=$(cqlsh scylladb -e "DESCRIBE KEYSPACES") 2> dev/null
        done
        sleep 5
        echo 'creating database...'
    cqlsh scylladb -f /opt/device-manager-scylla.cql

    exit;